
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package graficadora;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int anaranjado = 14;
  public static final int celeste = 10;
  public static final int poligono = 24;
  public static final int rojo = 8;
  public static final int ovalo = 26;
  public static final int circulo = 27;
  public static final int morado = 13;
  public static final int coma = 6;
  public static final int pcoma = 7;
  public static final int pacman = 28;
  public static final int negro = 12;
  public static final int linea = 22;
  public static final int rellena = 19;
  public static final int azul = 9;
  public static final int parAbre = 3;
  public static final int contorno = 20;
  public static final int estrella = 25;
  public static final int EOF = 0;
  public static final int parCierra = 4;
  public static final int gris = 18;
  public static final int error = 1;
  public static final int cuadrado = 2;
  public static final int trianguloRectangulo = 23;
  public static final int verde = 11;
  public static final int entero = 5;
  public static final int rectangulo = 21;
  public static final int amarillo = 17;
  public static final int rosado = 15;
  public static final int cafe = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cuadrado",
  "parAbre",
  "parCierra",
  "entero",
  "coma",
  "pcoma",
  "rojo",
  "azul",
  "celeste",
  "verde",
  "negro",
  "morado",
  "anaranjado",
  "rosado",
  "cafe",
  "amarillo",
  "gris",
  "rellena",
  "contorno",
  "rectangulo",
  "linea",
  "trianguloRectangulo",
  "poligono",
  "estrella",
  "ovalo",
  "circulo",
  "pacman"
  };
}

